services:
  finance-system-api:
    image: roxoo/finance-system-api:latest
    container_name: finance-system-api
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.finance-system-api.rule=Host(`finance-system-api.prxlab.app`)"
      - "traefik.http.routers.finance-system-api.entrypoints=websecure"
      - "traefik.http.routers.finance-system-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.finance-system-api.service=finance-system-api"

      # Service
      - "traefik.http.services.finance-system-api.loadbalancer.server.port=3000"

      # Middlewares
      - "traefik.http.routers.finance-system-api.middlewares=finance-cors"
      - "traefik.http.middlewares.finance-cors.headers.accessControlAllowOriginList=https://finance-system.prxlab.app,http://localhost:5173"
      - "traefik.http.middlewares.finance-cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.finance-cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.finance-cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.finance-cors.headers.accessControlMaxAge=100"

    ports:
      - "3000:3000"

    networks:
      - proxy
      - internal

  postgres:
    image: postgres:16
    container_name: finance-system-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "${POSTGRES_PORT}:5432"

networks:
  proxy:
    external: true
  internal:
    driver: bridge

volumes:
  postgres_data:
