services:
  finance-system-api:
    image: roxoo/finance-system-api:latest
    container_name: finance-system-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finance-system-api.rule=Host(`finance-system-api.prxlab.app`)"
      - "traefik.http.routers.finance-system-api.entrypoints=websecure"
      - "traefik.http.routers.finance-system-api.tls.certresolver=letsencrypt"
    networks:
      - proxy

networks:
  proxy:
    external: true