services:
  finance-system-api:
    image: roxoo/finance-system-api:latest
    container_name: finance-system-api
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finance-system-api.rule=Host(`finance-system-api.prxlab.app`)"
      - "traefik.http.routers.finance-system-api.entrypoints=websecure"
      - "traefik.http.routers.finance-system-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.finance-system-api.service=finance-system-api"
      - "traefik.http.services.finance-system-api.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

    networks:
      proxy:
        aliases:
          - finance-system-api
      internal:

  postgres:
    image: postgres:16
    container_name: finance-system-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "${POSTGRES_PORT}:5432"

networks:
  proxy:
    external: true
  internal:
    driver: bridge

volumes:
  postgres_data:
